### ISSUE TITLE
Bot initialization

### ISSUE THREAD

**Issue by mithintv** [mithintv/one-on-one#1]
### Tasks
- [ ] Bot sends optional welcome message in general
- [x] Slash command for pairing
- [ ] Bot posts pairings in channel it is in
