### ISSUE TITLE
Restrict Command

### ISSUE THREAD

**Issue by mithintv** [mithintv/one-on-one#15]
### Tasks
- [x] Create /restrict command for users
- [x] /restrict should only be valid in channels ONO bot is in
- [x] /restrict should accept a user or list of users in the channel it is called in
- [x] /restrict without parameters lists other users with whom the current user does not want to pair with
- [x] /restrict adds user or list of users to the restrict key for the current user that called it in the current channel they called it in DB
