### ISSUE TITLE
Rename Restrict

### ISSUE THREAD

**Issue by mithintv** [mithintv/one-on-one#18]
### Tasks
- [x] Rename /restrict command to /block
- [x] Rename responses accordingly
- [x] Rename bot settings on slack
