### ISSUE TITLE
Member Joined/Left Handler

### ISSUE THREAD

**Issue by mithintv** [mithintv/one-on-one#21]
### Tasks
- [x] Create listener for new members who join
- [x] Create DB defaults for new members
- [x] Set members as "inactive" upon leaving channel
- [x] Pair should only pair active members
- [x] If a member who previously left, rejoins, set them to "active"
