### ISSUE TITLE
Basic Jest Tests

### ISSUE THREAD

**Issue by mithintv** [mithintv/one-on-one#22]
### Tasks
- [x] Create test for bot joining brand channel
- [x] Create test for bot joining previously joined channel
- [x] Create test for bot leaving channel
- [x] Create test for members joining channel that bot has joined
- [x] Create test for members joining channel that bot has not joined
- [x] Create test for members leaving channel that bot has joined
- [x] Create test for members leaving channel that bot has not joined
