### ISSUE TITLE
Pair/Unpair Command

### ISSUE THREAD

**Issue by mithintv** [mithintv/one-on-one#25]
### Tasks
- [x] Rename /pair command for an individual to set themselves as active for pairing
- [x] Setup /pair in slack directory
- [x] /pair can only called on channels bot is in
- [x] /pair sets the active status of the individual in the channel to active if not already active.
- [x] Respond with success and status
- [x] Create /unpair command for an individual to set themselves as inactive for pairing
- [x] Setup /unpair in slack directory
- [x] /unpair can only called on channels bot is in
- [x] /unpair sets the active status of the individual in the channel to inactive if not already inactive.
- [x] Respond with success and status
- [x] Create unit tests for both commands
