### ISSUE TITLE
More Unit Tests

### ISSUE THREAD

**Issue by mithintv** [mithintv/one-on-one#26]
### Tasks
- [x] Refactor /frequency command
- [x] /frequency command for inactive users
- [x] Create unit tests for /frequency command
- [x] Refactor /block command
- [x] /block command for inactive users
- [x] Create unit tests for /block command
- [x] Refactor /unblock command
- [x] /block command for inactive users
- [x] Create unit tests for /unblock command
