### ISSUE TITLE
Prepare for Deployment

### ISSUE THREAD

**Issue by mithintv** [mithintv/one-on-one#29]
### Tasks
- [x] Remove unnecessary functions
- [x] Set interval and schedulers to days
- [x] Connect to DB
- [x] Deploy
- [x] Change domain paths on slack directory
- [x] Test install on channel
