### ISSUE TITLE
OAuth Connection

### ISSUE THREAD

**Issue by mithintv** [mithintv/one-on-one#3]
### Tasks
- [x] Connect OAuth process to DB
- [x] Store unique document per workspace
- [x] Delete document upon uninstallation
