### ISSUE TITLE
Mongo Tests

### ISSUE THREAD

**Issue by mithintv** [mithintv/one-on-one#30]
### Tasks
- [ ] Mongo Test for saving
- [ ] Mongo Test for fetching
- [ ] Mongo Test for updating
- [ ] Mongo Test for deleting
