### ISSUE TITLE
Delete Scheduled Messages

### ISSUE THREAD

**Issue by mithintv** [mithintv/one-on-one#32]
### Tasks
- [x] List scheduled messages upon leaving channel
- [x] Copy scheduled message ids
- [x] For each scheduled message by bot, delete them
- [x] Check for previously scheduled messages upon joining or rejoining channel
- [x] Delete previously scheduled messages upon joining or rejoining channel
- [x] Delete all messages sent in development
