### ISSUE TITLE
Optimize Block Command

### ISSUE THREAD

**Issue by mithintv** [mithintv/one-on-one#38]
### Tasks
- [x] Adjust DB schema for members to include names
- [x] Adjust joined event to save names of members in channel when bot joins channel
- [x] Adjust joined event to save names of members in channel when new members join channel
- [x] Adjust leave events to provide same functionality with new DB scheme
- [x] Adjust setBlock function to call saved names to cross check restrict list
- [x] Check setFrequency command works with new schema
- [x] Check setActive command works with new schema
- [x] Check setUnblock command works with new schema
- [x] Check filterActive function works with new schema
- [x] Check filterFrequency function works with new schema
- [x] Check filterRestriction function works with new schema
