### ISSUE TITLE
Handle Duplicates

### ISSUE THREAD

**Issue by mithintv** [mithintv/one-on-one#41]
### Tasks
- [x] Handle duplicates for /block command
- [x] Handle duplicates for /unblock command
- [x] Handle duplicates for /frequency command
- [x] Handle parameters for /pair command
- [x] Handle parameters for /unpair command
