### ISSUE TITLE
Status Command

### ISSUE THREAD

**Issue by mithintv** [mithintv/one-on-one#42]
### Tasks
- [x] Rename other commands w/ 'ono' prefix
- [x] Create /status command
- [x] /status should display summary of current frequency, 
- [x] /status should display next pairing date, 
- [x] /status should display isActive status, 
- [x] /status should display restriction list
- [x] Handle parameters for /status
