### ISSUE TITLE
Status Date/Last Pairing Date

### ISSUE THREAD

**Issue by mithintv** [mithintv/one-on-one#45]
### Tasks

- [x] Acquire local timezone per channel member for status command
- [x] Adjust date/time printed on status command to local time zone
- [x] Fix logic for last pairing date for each pair
