### ISSUE TITLE
Pairing Logic

### ISSUE THREAD

**Issue by mithintv** [mithintv/one-on-one#6]
### Tasks
- [x] Obtain members list in channel /pair is called in
- [x] Randomize members and return array
- [x] Post pairs of members in channel
