### ISSUE TITLE
Complex Pairing Logic

### ISSUE THREAD

**Issue by mithintv** [mithintv/one-on-one#8]
### Tasks
- [x] Allow users to filter other users that they don't want to pair with
- [x] Allow users to change frequency of individual one-on-ones
- [x] Allow users to set themselves as inActive in a channel with the bot
- [x] Store date of last pairing per individual in database
- [x] Filter pairs based on active status
- [x] Create test for filter function
- [x] Filter pairs based on date of individual frequencies
- [x] Create test for frequency function
- [x] Filter pairs based on date of restrictions list
- [x] Create test for restriction function
- [x] Have slack send recurring events that initiate pairing upon joining a channel
