### ISSUE TITLE
Frequency Command

### ISSUE THREAD

**Issue by mithintv** [mithintv/one-on-one#9]
### Tasks
- [x] Create frequency command for individuals in a channel
- [x] Frequency command should only work in channels with bot
- [x] Respond with failure message in channels without bot
- [x] Upon joining a channel, bot should store default frequencies of all members
- [x] Upon deletion from channel, set isActive to false
- [x] Command outputs current frequency if sent without parameters
- [x] Command w/ [number of days] parameter changes frequency to the input parameter
